"""All tables

Revision ID: 22af97caed7f
Revises: ac4c1b048b0f
Create Date: 2020-12-14 15:40:36.983560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22af97caed7f'
down_revision = 'ac4c1b048b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('QuestionType',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('function', sa.String(length=128), nullable=True),
    sa.Column('form', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('Question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('options', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('questiontype', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['questiontype'], ['QuestionType.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Answer',
    sa.Column('answeredquestion', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=256), nullable=True),
    sa.Column('case', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answeredquestion'], ['Question.id'], ),
    sa.ForeignKeyConstraint(['case'], ['Case.id'], ),
    sa.PrimaryKeyConstraint('answeredquestion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Answer')
    op.drop_table('Question')
    op.drop_table('QuestionType')
    op.drop_table('Case')
    # ### end Alembic commands ###
