"""Answer and Case tables

Revision ID: ac4c1b048b0f
Revises: e4843120708d
Create Date: 2020-12-14 15:37:16.281016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4c1b048b0f'
down_revision = 'e4843120708d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Answer',
    sa.Column('answeredquestion', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=256), nullable=True),
    sa.Column('case', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['answeredquestion'], ['Question.id'], ),
    sa.ForeignKeyConstraint(['case'], ['Case.id'], ),
    sa.PrimaryKeyConstraint('answeredquestion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Answer')
    op.drop_table('Case')
    # ### end Alembic commands ###
