"""first migration

Revision ID: c49480436924
Revises: 819b1fceba3e
Create Date: 2021-01-06 14:17:34.192182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49480436924'
down_revision = '819b1fceba3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Case',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('QuestionType',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('function', sa.String(length=128), nullable=True),
    sa.Column('form', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('Question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('options', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('questiontype', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['questiontype'], ['QuestionType.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Answer',
    sa.Column('answeredquestion', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=256), nullable=True),
    sa.Column('case', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['answeredquestion'], ['Question.id'], ),
    sa.ForeignKeyConstraint(['case'], ['Case.id'], ),
    sa.PrimaryKeyConstraint('answeredquestion', 'case')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Answer')
    op.drop_table('Question')
    op.drop_table('QuestionType')
    op.drop_table('Case')
    # ### end Alembic commands ###
