"""QuestionType and Question tables

Revision ID: e4843120708d
Revises: fab500308f2c
Create Date: 2020-12-14 14:40:28.416717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4843120708d'
down_revision = 'fab500308f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuestionType',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('function', sa.String(length=128), nullable=True),
    sa.Column('form', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('Question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('options', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('questiontype', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['questiontype'], ['QuestionType.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Question')
    op.drop_table('QuestionType')
    # ### end Alembic commands ###
