"""Added reversed score field to question model

Revision ID: 0dafc6d9292d
Revises: f8ba41ac9536
Create Date: 2021-03-17 13:06:20.735319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dafc6d9292d'
down_revision = 'f8ba41ac9536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Question', sa.Column('reversed_score', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Question', 'reversed_score')
    # ### end Alembic commands ###
