"""Added code_used and list_selected field to case

Revision ID: 48a3b8b0c0bb
Revises: 92d3b23fc253
Create Date: 2021-03-01 12:13:32.369813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a3b8b0c0bb'
down_revision = '92d3b23fc253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Case', sa.Column('code_used', sa.Integer(), nullable=True))
    op.add_column('Case', sa.Column('list_selected', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Case', 'Code', ['code_used'], ['id'])
    op.create_foreign_key(None, 'Case', 'QuestionList', ['list_selected'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Case', type_='foreignkey')
    op.drop_constraint(None, 'Case', type_='foreignkey')
    op.drop_column('Case', 'list_selected')
    op.drop_column('Case', 'code_used')
    # ### end Alembic commands ###
