"""Added weights to question and group

Revision ID: 6520f1f62501
Revises: 48a3b8b0c0bb
Create Date: 2021-03-05 14:01:09.187430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6520f1f62501'
down_revision = '48a3b8b0c0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Question', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('QuestionGroup', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('QuestionGroup', 'weight')
    op.drop_column('Question', 'weight')
    # ### end Alembic commands ###
