"""Added branch, company size and participant function to case model

Revision ID: 6e0b582c34af
Revises: 49301064e852
Create Date: 2021-03-26 13:36:48.612277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0b582c34af'
down_revision = '49301064e852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Case', sa.Column('branch', sa.String(), nullable=True))
    op.add_column('Case', sa.Column('company_size', sa.String(), nullable=True))
    op.add_column('Case', sa.Column('participant_function', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Case', 'participant_function')
    op.drop_column('Case', 'company_size')
    op.drop_column('Case', 'branch')
    # ### end Alembic commands ###
