"""Added value column to LikertOption

Revision ID: 82cebf97546b
Revises: b37ecb1ddd8a
Create Date: 2021-03-08 15:15:51.319089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cebf97546b'
down_revision = 'b37ecb1ddd8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LikertOption', sa.Column('value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LikertOption', 'value')
    # ### end Alembic commands ###
