"""Initial migration

Revision ID: b6dc8d9ae1da
Revises: 
Create Date: 2021-02-10 12:19:21.016134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6dc8d9ae1da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Case',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('QuestionGroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('group_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('QuestionType',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('function', sa.String(length=128), nullable=True),
    sa.Column('form', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('Question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('options', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('questiontype', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['questiontype'], ['QuestionType.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Answer',
    sa.Column('answeredquestion', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=256), nullable=True),
    sa.Column('case', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['answeredquestion'], ['Question.id'], ),
    sa.ForeignKeyConstraint(['case'], ['Case.id'], ),
    sa.PrimaryKeyConstraint('answeredquestion', 'case')
    )
    op.create_table('QuestionGroupQuestion',
    sa.Column('question_group_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_group_id'], ['QuestionGroup.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['Question.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('QuestionGroupQuestion')
    op.drop_table('Answer')
    op.drop_table('Question')
    op.drop_table('QuestionType')
    op.drop_table('QuestionGroup')
    op.drop_table('Case')
    # ### end Alembic commands ###
